// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOE7HK1Z_nE7Vovr2Y2mY5SVixKHFV-fs',
    appId: '1:199928698380:web:717a8ce1d3cd653e6ac029',
    messagingSenderId: '199928698380',
    projectId: 'base1-55ca6',
    authDomain: 'base1-55ca6.firebaseapp.com',
    databaseURL: 'https://base1-55ca6-default-rtdb.firebaseio.com',
    storageBucket: 'base1-55ca6.appspot.com',
    measurementId: 'G-1E5BJS9LCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRgx05-l7az9k-JGt80pP5JYr6xkhIbfg',
    appId: '1:199928698380:android:842617e0548ad4ff6ac029',
    messagingSenderId: '199928698380',
    projectId: 'base1-55ca6',
    databaseURL: 'https://base1-55ca6-default-rtdb.firebaseio.com',
    storageBucket: 'base1-55ca6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxcnmWAwKNZuvd1L6KNo8-uS80bjviaxQ',
    appId: '1:199928698380:ios:a5f284e03c9c27606ac029',
    messagingSenderId: '199928698380',
    projectId: 'base1-55ca6',
    databaseURL: 'https://base1-55ca6-default-rtdb.firebaseio.com',
    storageBucket: 'base1-55ca6.appspot.com',
    iosClientId: '199928698380-bjr4qit11akf744ladqiij08c052esce.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomasoleasapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxcnmWAwKNZuvd1L6KNo8-uS80bjviaxQ',
    appId: '1:199928698380:ios:a5f284e03c9c27606ac029',
    messagingSenderId: '199928698380',
    projectId: 'base1-55ca6',
    databaseURL: 'https://base1-55ca6-default-rtdb.firebaseio.com',
    storageBucket: 'base1-55ca6.appspot.com',
    iosClientId: '199928698380-bjr4qit11akf744ladqiij08c052esce.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomasoleasapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOE7HK1Z_nE7Vovr2Y2mY5SVixKHFV-fs',
    appId: '1:199928698380:web:feb67593f2b9888e6ac029',
    messagingSenderId: '199928698380',
    projectId: 'base1-55ca6',
    authDomain: 'base1-55ca6.firebaseapp.com',
    databaseURL: 'https://base1-55ca6-default-rtdb.firebaseio.com',
    storageBucket: 'base1-55ca6.appspot.com',
    measurementId: 'G-LG2P2C54ME',
  );

}